name: Hello World

on:
  push:
    branches: 
      - main
      - benchmarks_in_parallel
  pull_request:
    branches: 
      - main
      - benchmarks_in_parallel

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
    - name: Say Hello
      run: |
      echo "Hello World"
      ls