name: "Run benchmark without Docker"
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, edited]
  push:
    branches:
      - diff
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  build-job:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'Update performance results in README.md'
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      
      - name: Setup project dependencies
        run: |
          # Add commands to install necessary dependencies
          # For example:
          # sudo apt-get update
          # sudo apt-get install -y <required-packages>
      
      - name: Build project
        run: |
          # Add commands to build your project
          # For example:
          # make build
          # or
          # npm install && npm run build
      
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            # Specify paths to cache, for example:
            # build/
            # dist/
            # node_modules/
          key: ${{ runner.os }}-build-${{ github.sha }}

  benchmark-job:
    needs: build-job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [apollo_server, caliban, netflix_dgs, gqlgen, tailcall, async_graphql, hasura, graphql_jit]
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
      
      - name: Restore cached build artifacts
        uses: actions/cache@v3
        with:
          path: |
            # Specify the same paths as in the build-job
          key: ${{ runner.os }}-build-${{ github.sha }}
      
      - name: Run benchmarks
        run: |
          # Add commands to run your benchmarks
          # For example:
          # ./graphql/${{ matrix.service }}/setup.sh
          # bash run_benchmarks.sh ${{ matrix.service }}
      
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: bench*.txt

  analyze:
    needs: benchmark-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      
      - name: Restore cached build artifacts
        uses: actions/cache@v3
        with:
          path: |
            # Specify the same paths as in the build-job
          key: ${{ runner.os }}-build-${{ github.sha }}
      
      - name: Download all benchmark results
        uses: actions/download-artifact@v3
        with:
          name: benchmark-results
          path: .
      
      - name: Analyze results
        run: |
          bash run_analyze_script.sh
      
      - name: Print benchmark results
        run: cat ./results.md
      
      - name: Comment benchmark results on PR
        if: github.event_name == 'pull_request_target'
        uses: peter-evans/commit-comment@v3
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          body-path: "results.md"
          reactions: eyes
      
      - name: Commit and push changes (on main branch)
        if: github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_author: Author <actions@github.com>
          commit_message: "Update performance results in README.md"